print("Hello World")
print("My name is Michael Lumula")
print("I Love Devops")
print("Michael is 27 years old")
print("I will be the best one day when it come to tasks related to Devops Engineering")
print("Hello Michael")
